name: broker_mobile
description: "SAS Broker App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.6.0
  grpc: ^4.1.0
  protobuf: ^4.1.0
  fixnum: ^1.1.0
  flutter_dotenv: ^6.0.0
  shared_preferences: ^2.2.2
  jwt_decoder: ^2.0.1
  flutter_typeahead: ^5.2.0
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
